spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://etms.chubebdi6f7l.ap-south-1.rds.amazonaws.com:5432/etmsdb
    username: etms_user
    password: CHnMwmBYnZ6EGZSZEayO
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

server:
  port: 8080

