spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://etms.chubebdi6f7l.ap-south-1.rds.amazonaws.com:5432/etmsdb
    username: etms_user
    password: CHnMwmBYnZ6EGZSZEayO
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
      auto-commit: true
      connection-test-query: SELECT 1
      pool-name: HikariPool-UserService

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true

server:
  port: 8080

