version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: traffic-monitoring-db
    environment:
      POSTGRES_DB: traffic_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic-monitoring-userservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://etms.chubebdi6f7l.ap-south-1.rds.amazonaws.com:5432/etmsdb
      SPRING_DATASOURCE_USERNAME: etms_user
      SPRING_DATASOURCE_PASSWORD: CHnMwmBYnZ6EGZSZEayO
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: "true"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tms-network
    restart: unless-stopped

networks:
  tms-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

